#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var easterEggs = [
  ["I'm hungry","why is history boring?"],
  ["I like chocolate strawberries", "do you prefer icecream or milkshake?"]

];

function print(message) {
  process.stdout.write(message + "\n");
}

print(c.clear + c.multi("Welcome to Candy Land!" + "\n");
